@baseUrl = http://localhost:3000/api
@token = {{login.response.body.accessToken}}

### Swagger UI
GET {{baseUrl}}/docs

### Health
GET {{baseUrl}}/health

### Register client
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "client1@taxi.local",
  "password": "password123",
  "role": "CLIENT"
}

### Register driver
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "driver1@taxi.local",
  "password": "password123",
  "role": "DRIVER"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "client1@taxi.local",
  "password": "password123"
}

### Who am I
# @name me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}

### Driver online
PATCH {{baseUrl}}/drivers/me/availability
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "online": true
}

### Driver location
PATCH {{baseUrl}}/drivers/me/location
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "latitude": 43.238949,
  "longitude": 76.889709
}

### Create order
# @name createOrder
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "passengerId": "{{me.response.body.id}}",
  "cityId": "almaty",
  "pickupLatitude": 43.238949,
  "pickupLongitude": 76.889709,
  "dropoffLatitude": 43.240978,
  "dropoffLongitude": 76.924758,
  "distanceKm": 8.5,
  "durationMinutes": 18
}

### Search driver
POST {{baseUrl}}/orders/{{createOrder.response.body.id}}/search-driver
Authorization: Bearer {{token}}

### Update status
PATCH {{baseUrl}}/orders/{{createOrder.response.body.id}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "IN_PROGRESS"
}
