@baseUrl = http://localhost:3000/api
@token = {{login.response.body.accessToken}}

### Swagger UI
GET {{baseUrl}}/docs

### Health
GET {{baseUrl}}/health

### Register (optional)
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "newuser@taxi.local",
  "password": "password123",
  "role": "CLIENT"
}

### Login (demo client)
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "client@taxi.local",
  "password": "client123"
}

### Who am I
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}

### Driver online
PATCH {{baseUrl}}/drivers/3fbf77cb-0b80-4b1e-84a4-c56b9d0f4da0/availability
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "online": true
}

### Driver location
PATCH {{baseUrl}}/drivers/3fbf77cb-0b80-4b1e-84a4-c56b9d0f4da0/location
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "latitude": 43.238949,
  "longitude": 76.889709
}

### Create order
# @name createOrder
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "passengerId": "f3a51fc6-fd09-4c32-8c6f-46fd019e3472",
  "cityId": "almaty",
  "pickupLatitude": 43.238949,
  "pickupLongitude": 76.889709,
  "dropoffLatitude": 43.240978,
  "dropoffLongitude": 76.924758,
  "distanceKm": 8.5,
  "durationMinutes": 18
}

### Search driver
POST {{baseUrl}}/orders/{{createOrder.response.body.id}}/search-driver
Authorization: Bearer {{token}}

### Update status
PATCH {{baseUrl}}/orders/{{createOrder.response.body.id}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "IN_PROGRESS"
}
